---
- name: Add Docker GPG key
  become: yes
  become_user: root
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: Create a list file for Docker
  become: yes
  become_user: root
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main"

- name: Get the uname
  command: "uname -r"
  register: uname

- debug: var=uname

- name: Install Dependencies and Docker
  become: yes
  become_user: root
  apt: update_cache=yes name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - linux-image-extra-virtual
    - linux-image-extra-{{uname.stdout}}
    - apparmor
    - docker-engine

- name: Start the docker daemon
  become: yes
  become_user: root
  service: name=docker state=started

- name: Verify docker is installed correctly
  become: yes
  become_user: root
  command: docker run hello-world
