---
- name: Get the latest release of nvidia-docker
  get_url: "dest=/tmp/nvidia-docker.deb url=https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb"

- name: Install nvidia-docker
  command: dpkg -i /tmp/nvidia-docker.deb

- name: Run the nvidia-smi test
  command: nvidia-docker run --rm nvidia/cuda:7.0-runtime nvidia-smi
